development:
  host: localhost
  database: polco2_development

test:
  host: localhost
  database: polco2_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>